AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Textbook Study Buddy MVP Backend

Globals:
  Function:
    Timeout: 30
    Runtime: nodejs18.x
    MemorySize: 512
    Environment:
      Variables:
        PDF_BUCKET: !Ref TextbookPDFBucket
        CONTENT_TABLE: !Ref TextbookContentTable
        PROGRESS_TABLE: !Ref UserProgressTable

Resources:
  # S3 Bucket for PDFs
  TextbookPDFBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - "*"
            AllowedMethods:
              - PUT
              - GET
              - HEAD
            AllowedOrigins:
              - "*"
            MaxAge: 3000

  # DynamoDB Tables
  TextbookContentTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
        - AttributeName: type
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: TypeIndex
          KeySchema:
            - AttributeName: type
              KeyType: HASH
            - AttributeName: PK
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

  UserProgressTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE

  # API Gateway
  TextbookApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      Cors:
        AllowMethods: "'*'"
        AllowHeaders: "'*'"
        AllowOrigin: "'*'"

  # Lambda Functions
  UploadFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
    Properties:
      CodeUri: ./
      Handler: src/handlers/upload.handler
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref TextbookPDFBucket
        - DynamoDBCrudPolicy:
            TableName: !Ref TextbookContentTable
      Events:
        Upload:
          Type: Api
          Properties:
            RestApiId: !Ref TextbookApi
            Path: /upload
            Method: post

  ContentFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
    Properties:
      CodeUri: ./
      Handler: src/handlers/content.handler
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref TextbookContentTable
      Events:
        GetContent:
          Type: Api
          Properties:
            RestApiId: !Ref TextbookApi
            Path: /content/{bookId}
            Method: get

  AskFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
    Properties:
      CodeUri: ./
      Handler: src/handlers/ask.handler
      Timeout: 60
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref TextbookContentTable
        - Statement:
            - Effect: Allow
              Action:
                - bedrock:InvokeModel
              Resource: '*'
      Events:
        Ask:
          Type: Api
          Properties:
            RestApiId: !Ref TextbookApi
            Path: /ask
            Method: post

  SummarizeFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
    Properties:
      CodeUri: ./
      Handler: src/handlers/summarize.handler
      Timeout: 60
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref TextbookContentTable
        - Statement:
            - Effect: Allow
              Action:
                - bedrock:InvokeModel
              Resource: '*'
      Events:
        Summarize:
          Type: Api
          Properties:
            RestApiId: !Ref TextbookApi
            Path: /summarize
            Method: post

  ListBooksFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
    Properties:
      CodeUri: ./
      Handler: src/handlers/listBooks.handler
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref TextbookContentTable
      Events:
        ListBooks:
          Type: Api
          Properties:
            RestApiId: !Ref TextbookApi
            Path: /books
            Method: get

  ProcessPdfFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        External:
          - "canvas"
    Properties:
      CodeUri: ./
      Handler: src/handlers/processPdf.handler
      Timeout: 300
      MemorySize: 1024
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref TextbookPDFBucket
        - DynamoDBCrudPolicy:
            TableName: !Ref TextbookContentTable
      Events:
        S3Upload:
          Type: S3
          Properties:
            Bucket: !Ref TextbookPDFBucket
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: suffix
                    Value: .pdf

  ReprocessPdfFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        External:
          - "canvas"
    Properties:
      CodeUri: ./
      Handler: src/handlers/reprocessPdf.handler
      Timeout: 300
      MemorySize: 1024
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref TextbookPDFBucket
        - DynamoDBCrudPolicy:
            TableName: !Ref TextbookContentTable
      Events:
        Reprocess:
          Type: Api
          Properties:
            RestApiId: !Ref TextbookApi
            Path: /reprocess
            Method: post

Outputs:
  ApiEndpoint:
    Description: API Gateway endpoint URL
    Value: !Sub 'https://${TextbookApi}.execute-api.${AWS::Region}.amazonaws.com/prod/'
  PDFBucket:
    Description: S3 bucket for PDFs
    Value: !Ref TextbookPDFBucket
