AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Textbook Study Buddy MVP Backend

Globals:
  Function:
    Timeout: 30
    Runtime: nodejs18.x
    MemorySize: 512
    Environment:
      Variables:
        PDF_BUCKET: !Ref TextbookPDFBucket
        CONTENT_TABLE: !Ref TextbookContentTable
        PROGRESS_TABLE: !Ref UserProgressTable

Resources:
  # S3 Bucket for PDFs
  TextbookPDFBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  # DynamoDB Tables
  TextbookContentTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE

  UserProgressTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE

  # API Gateway
  TextbookApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      Cors:
        AllowMethods: "'*'"
        AllowHeaders: "'*'"
        AllowOrigin: "'*'"

  # Lambda Functions
  UploadFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
    Properties:
      CodeUri: ./
      Handler: src/handlers/upload.handler
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref TextbookPDFBucket
        - DynamoDBCrudPolicy:
            TableName: !Ref TextbookContentTable
      Events:
        Upload:
          Type: Api
          Properties:
            RestApiId: !Ref TextbookApi
            Path: /upload
            Method: post

  ContentFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
    Properties:
      CodeUri: ./
      Handler: src/handlers/content.handler
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref TextbookContentTable
      Events:
        GetContent:
          Type: Api
          Properties:
            RestApiId: !Ref TextbookApi
            Path: /content/{bookId}
            Method: get

  AskFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
    Properties:
      CodeUri: ./
      Handler: src/handlers/ask.handler
      Timeout: 60
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref TextbookContentTable
        - Statement:
            - Effect: Allow
              Action:
                - bedrock:InvokeModel
              Resource: '*'
      Events:
        Ask:
          Type: Api
          Properties:
            RestApiId: !Ref TextbookApi
            Path: /ask
            Method: post

  SummarizeFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
    Properties:
      CodeUri: ./
      Handler: src/handlers/summarize.handler
      Timeout: 60
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref TextbookContentTable
        - Statement:
            - Effect: Allow
              Action:
                - bedrock:InvokeModel
              Resource: '*'
      Events:
        Summarize:
          Type: Api
          Properties:
            RestApiId: !Ref TextbookApi
            Path: /summarize
            Method: post

Outputs:
  ApiEndpoint:
    Description: API Gateway endpoint URL
    Value: !Sub 'https://${TextbookApi}.execute-api.${AWS::Region}.amazonaws.com/prod/'
  PDFBucket:
    Description: S3 bucket for PDFs
    Value: !Ref TextbookPDFBucket
