AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Textbook Study Buddy MVP Backend

Parameters:
  NotificationEmail:
    Type: String
    Description: Email address for EPUB processing failure notifications
    Default: ""

Conditions:
  HasNotificationEmail: !Not [!Equals [!Ref NotificationEmail, ""]]

Globals:
  Function:
    Timeout: 30
    Runtime: nodejs18.x
    MemorySize: 512
    Environment:
      Variables:
        BOOKS_BUCKET: !Ref TextbookBucket
        CONTENT_TABLE: !Ref TextbookContentTable
        PROGRESS_TABLE: !Ref UserProgressTable

Resources:
  # S3 Bucket for EPUB files
  TextbookBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - "*"
            AllowedMethods:
              - PUT
              - GET
              - HEAD
            AllowedOrigins:
              - "*"
            MaxAge: 3000

  # DynamoDB Tables
  TextbookContentTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
        - AttributeName: type
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: TypeIndex
          KeySchema:
            - AttributeName: type
              KeyType: HASH
            - AttributeName: PK
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

  UserProgressTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE

  # API Gateway
  TextbookApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      Cors:
        AllowMethods: "'*'"
        AllowHeaders: "'*'"
        AllowOrigin: "'*'"

  # Lambda Functions
  UploadFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
    Properties:
      CodeUri: ./
      Handler: src/handlers/upload.handler
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref TextbookBucket
        - DynamoDBCrudPolicy:
            TableName: !Ref TextbookContentTable
      Events:
        Upload:
          Type: Api
          Properties:
            RestApiId: !Ref TextbookApi
            Path: /upload
            Method: post

  ContentFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
    Properties:
      CodeUri: ./
      Handler: src/handlers/content.handler
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref TextbookContentTable
        - S3ReadPolicy:
            BucketName: !Ref TextbookBucket
      Events:
        GetContent:
          Type: Api
          Properties:
            RestApiId: !Ref TextbookApi
            Path: /content/{bookId}
            Method: get

  AskFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
    Properties:
      CodeUri: ./
      Handler: src/handlers/ask.handler
      Timeout: 60
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref TextbookContentTable
        - S3ReadPolicy:
            BucketName: !Ref TextbookBucket
        - Statement:
            - Effect: Allow
              Action:
                - bedrock:InvokeModel
              Resource: '*'
            - Effect: Allow
              Action:
                - aws-marketplace:ViewSubscriptions
                - aws-marketplace:Subscribe
              Resource: '*'
      Events:
        Ask:
          Type: Api
          Properties:
            RestApiId: !Ref TextbookApi
            Path: /ask
            Method: post

  SummarizeFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
    Properties:
      CodeUri: ./
      Handler: src/handlers/summarize.handler
      Timeout: 60
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TextbookContentTable
        - S3ReadPolicy:
            BucketName: !Ref TextbookBucket
        - Statement:
            - Effect: Allow
              Action:
                - bedrock:InvokeModel
              Resource: '*'
            - Effect: Allow
              Action:
                - aws-marketplace:ViewSubscriptions
                - aws-marketplace:Subscribe
              Resource: '*'
      Events:
        Summarize:
          Type: Api
          Properties:
            RestApiId: !Ref TextbookApi
            Path: /summarize
            Method: post

  GenerateQuizFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
    Properties:
      CodeUri: ./
      Handler: src/handlers/generateQuiz.handler
      Timeout: 60
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TextbookContentTable
        - S3ReadPolicy:
            BucketName: !Ref TextbookBucket
        - Statement:
            - Effect: Allow
              Action:
                - bedrock:InvokeModel
              Resource: '*'
            - Effect: Allow
              Action:
                - aws-marketplace:ViewSubscriptions
                - aws-marketplace:Subscribe
              Resource: '*'
      Events:
        GenerateQuiz:
          Type: Api
          Properties:
            RestApiId: !Ref TextbookApi
            Path: /quiz/generate
            Method: post

  EvaluateAnswerFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
    Properties:
      CodeUri: ./
      Handler: src/handlers/evaluateAnswer.handler
      Timeout: 30
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - bedrock:InvokeModel
              Resource: '*'
            - Effect: Allow
              Action:
                - aws-marketplace:ViewSubscriptions
                - aws-marketplace:Subscribe
              Resource: '*'
      Events:
        EvaluateAnswer:
          Type: Api
          Properties:
            RestApiId: !Ref TextbookApi
            Path: /quiz/evaluate
            Method: post

  HintFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
    Properties:
      CodeUri: ./
      Handler: src/handlers/hint.handler
      Timeout: 60
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref TextbookContentTable
        - S3ReadPolicy:
            BucketName: !Ref TextbookBucket
        - Statement:
            - Effect: Allow
              Action:
                - bedrock:InvokeModel
              Resource: '*'
            - Effect: Allow
              Action:
                - aws-marketplace:ViewSubscriptions
                - aws-marketplace:Subscribe
              Resource: '*'
      Events:
        Hint:
          Type: Api
          Properties:
            RestApiId: !Ref TextbookApi
            Path: /hint
            Method: post

  ListBooksFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
    Properties:
      CodeUri: ./
      Handler: src/handlers/listBooks.handler
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref TextbookContentTable
      Events:
        ListBooks:
          Type: Api
          Properties:
            RestApiId: !Ref TextbookApi
            Path: /books
            Method: get

  BookStatusFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
    Properties:
      CodeUri: ./
      Handler: src/handlers/bookStatus.handler
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref TextbookContentTable
      Events:
        GetStatus:
          Type: Api
          Properties:
            RestApiId: !Ref TextbookApi
            Path: /books/{bookId}/status
            Method: get

  InspectContentFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
    Properties:
      CodeUri: ./
      Handler: src/handlers/inspectContent.handler
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref TextbookContentTable
      Events:
        InspectContent:
          Type: Api
          Properties:
            RestApiId: !Ref TextbookApi
            Path: /inspect/{bookId}
            Method: get

  ReprocessFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
    Properties:
      CodeUri: ./
      Handler: src/handlers/reprocess.handler
      Environment:
        Variables:
          TABLE_NAME: !Ref TextbookContentTable
          BUCKET_NAME: !Ref TextbookBucket
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref TextbookBucket
        - DynamoDBCrudPolicy:
            TableName: !Ref TextbookContentTable
      Events:
        Reprocess:
          Type: Api
          Properties:
            RestApiId: !Ref TextbookApi
            Path: /books/{bookId}/reprocess
            Method: post

  HideBookFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
    Properties:
      CodeUri: ./
      Handler: src/handlers/hideBook.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TextbookContentTable
      Events:
        HideBook:
          Type: Api
          Properties:
            RestApiId: !Ref TextbookApi
            Path: /books/{bookId}/hide
            Method: patch

  # SNS Topic for EPUB Processing Notifications
  EpubProcessingTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: EPUB Processing Notifications

  EpubProcessingEmailSubscription:
    Type: AWS::SNS::Subscription
    Condition: HasNotificationEmail
    Properties:
      Protocol: email
      TopicArn: !Ref EpubProcessingTopic
      Endpoint: !Ref NotificationEmail

  ProcessEpubFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
    Properties:
      CodeUri: ./
      Handler: src/handlers/processEpub.handler
      Timeout: 300
      MemorySize: 1024
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref TextbookBucket
        - DynamoDBCrudPolicy:
            TableName: !Ref TextbookContentTable
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt EpubProcessingTopic.TopicName

  ProcessTexFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        External:
          - jsdom
    Properties:
      CodeUri: ./
      Handler: src/handlers/processTex.handler
      Timeout: 300
      MemorySize: 2048
      Layers:
        - !Ref LaTeXMLLayer
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref TextbookBucket
        - DynamoDBCrudPolicy:
            TableName: !Ref TextbookContentTable
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt EpubProcessingTopic.TopicName

  ProcessEpubFunctionEventInvokeConfig:
    Type: AWS::Lambda::EventInvokeConfig
    DependsOn:
      - ProcessEpubFunction
      - EpubProcessingTopic
    Properties:
      FunctionName: !Ref ProcessEpubFunction
      Qualifier: $LATEST
      DestinationConfig:
        OnFailure:
          Destination: !Ref EpubProcessingTopic

  ProcessTexFunctionEventInvokeConfig:
    Type: AWS::Lambda::EventInvokeConfig
    DependsOn:
      - ProcessTexFunction
      - EpubProcessingTopic
    Properties:
      FunctionName: !Ref ProcessTexFunction
      Qualifier: $LATEST
      DestinationConfig:
        OnFailure:
          Destination: !Ref EpubProcessingTopic

  ProcessEpubFunctionS3Permission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref ProcessEpubFunction
      Action: lambda:InvokeFunction
      Principal: s3.amazonaws.com
      SourceArn: !Sub 'arn:aws:s3:::${TextbookBucket}'

  ProcessTexFunctionS3Permission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref ProcessTexFunction
      Action: lambda:InvokeFunction
      Principal: s3.amazonaws.com
      SourceArn: !Sub 'arn:aws:s3:::${TextbookBucket}'

  # Lambda Layer for LaTeXML
  LaTeXMLLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: latexml-layer
      Description: LaTeXML and dependencies for TeX processing
      ContentUri: ./layers/latexml/
      CompatibleRuntimes:
        - nodejs18.x
    Metadata:
      BuildMethod: makefile

  # Custom resource to configure S3 notifications
  S3NotificationCustomResource:
    Type: Custom::S3BucketNotification
    DependsOn: 
      - ProcessEpubFunctionS3Permission
      - ProcessTexFunctionS3Permission
    Properties:
      ServiceToken: !GetAtt S3NotificationFunction.Arn
      BucketName: !Ref TextbookBucket
      EpubLambdaArn: !GetAtt ProcessEpubFunction.Arn
      TexLambdaArn: !GetAtt ProcessTexFunction.Arn

  S3NotificationFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.9
      Handler: index.handler
      InlineCode: |
        import json
        import boto3
        import urllib3

        s3 = boto3.client('s3')
        http = urllib3.PoolManager()

        def send_response(event, context, status, data={}):
            body = json.dumps({
                'Status': status,
                'Reason': f'See CloudWatch Log Stream: {context.log_stream_name}',
                'PhysicalResourceId': context.log_stream_name,
                'StackId': event['StackId'],
                'RequestId': event['RequestId'],
                'LogicalResourceId': event['LogicalResourceId'],
                'Data': data
            })
            http.request('PUT', event['ResponseURL'], body=body)

        def handler(event, context):
            try:
                bucket = event['ResourceProperties']['BucketName']
                
                if event['RequestType'] == 'Delete':
                    s3.put_bucket_notification_configuration(
                        Bucket=bucket,
                        NotificationConfiguration={}
                    )
                    send_response(event, context, 'SUCCESS')
                    return
                
                epub_lambda_arn = event['ResourceProperties']['EpubLambdaArn']
                tex_lambda_arn = event['ResourceProperties']['TexLambdaArn']
                
                s3.put_bucket_notification_configuration(
                    Bucket=bucket,
                    NotificationConfiguration={
                        'LambdaFunctionConfigurations': [
                            {
                                'LambdaFunctionArn': epub_lambda_arn,
                                'Events': ['s3:ObjectCreated:*'],
                                'Filter': {
                                    'Key': {
                                        'FilterRules': [{'Name': 'suffix', 'Value': '.epub'}]
                                    }
                                }
                            },
                            {
                                'LambdaFunctionArn': tex_lambda_arn,
                                'Events': ['s3:ObjectCreated:*'],
                                'Filter': {
                                    'Key': {
                                        'FilterRules': [{'Name': 'suffix', 'Value': '.tex'}]
                                    }
                                }
                            },
                            {
                                'LambdaFunctionArn': tex_lambda_arn,
                                'Events': ['s3:ObjectCreated:*'],
                                'Filter': {
                                    'Key': {
                                        'FilterRules': [{'Name': 'suffix', 'Value': '.latex'}]
                                    }
                                }
                            }
                        ]
                    }
                )
                send_response(event, context, 'SUCCESS')
            except Exception as e:
                print(f'Error: {e}')
                send_response(event, context, 'FAILED')
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref TextbookBucket
        - Statement:
            - Effect: Allow
              Action:
                - s3:PutBucketNotification
                - s3:GetBucketNotification
              Resource: !Sub 'arn:aws:s3:::${TextbookBucket}'

Outputs:
  ApiEndpoint:
    Description: API Gateway endpoint URL
    Value: !Sub 'https://${TextbookApi}.execute-api.${AWS::Region}.amazonaws.com/prod/'
  BooksBucket:
    Description: S3 bucket for EPUB files
    Value: !Ref TextbookBucket
  EpubProcessingTopicArn:
    Description: SNS Topic ARN for EPUB processing notifications
    Value: !Ref EpubProcessingTopic
  ProcessEpubFunctionArn:
    Description: Lambda function ARN for S3 notification configuration
    Value: !GetAtt ProcessEpubFunction.Arn
  ProcessEpubFunctionName:
    Description: Lambda function name for S3 notification configuration
    Value: !Ref ProcessEpubFunction
